app_name: hello_webapp
repo_url: git@github.com:mhfowler/ansible-flask-react-tachyons.git
repo_remote: origin
repo_branch: master
src_dir: /srv/hello_webapp
backend_dir: /srv/hello_webapp/backend
log_dir: /srv/log
aws_key_name: successkit
aws_security_group: webapp-security-group
aws_instance_name: aws_default
aws_key_location: /Users/maxfowler/Dropbox/base/freelance/success_kit/ansible-flask-template/backend/devops/secret_files/successkit.pem
aws_subnet: subnet-72cdbd5f
prod_url: http://52.91.169.141/